### ISSUE TITLE
Is it possible to write Tabular types to .tex?

### ISSUE THREAD

**Issue by ezgikurt** [rened/LaTeX.jl#14]
Hi, is it possible to have the output as .tex files (i need to compile them later, together with other figures & tables)? When i do `report(Tabular(Array))` the output is a string, but when i try `writedlm("example.tex", report(Tabular(Array))` the outcome is a .tex file where each letter is printed on a line. 

I have been able to do it with `open("example.tex", "w")` `write()` `close()` sequence but I was wondering if there is a neater option?

**Comment by rened** [comment]
That is caused by `writedlm`. Use `write` instead.
