### ISSUE TITLE
Is this project still considered active? 

### ISSUE THREAD

**Issue by rapus95** [rened/LaTeX.jl#8]
Hey, i just wondered if the project is still being maintained since there was no commit in the last 8months or, if not, whether you can refer to an active alternative.

**Comment by rened** [comment]
Slightly dormant but still alive. I will add the ability to use `Plots.jl` plots shortly. Anything else you have in mind / would like to see?

**Comment by rapus95** [comment]
Right now i'm aiming for using PyPlot and LaTeX together. Since I'm pretty new to this lib I'm not exactly sure about its capabilities. Right now I'm thinking about using LaTeX templates (like having a template given that has to be filled with data/images) but that can be achieved very easily by using temporary files and regex/concat and dictionaries I guess.
From my usage till now, it'd be nice to remove the necessity of LegacyStrings.jl for Julia 0.5 and 0.6 and it'd be nice to have an overview over the latex packages that are being needed by this lib.
Especially an update for the new 0.6 version of julia would be pretty awesome

**Comment by rened** [comment]
Once I have added `Plots.jl` you could use `PyPlot` as one of its backends. #9

For the templates, you could simply write Julia functions for your templates, using `Latex.jl`, that insert the actual data / images where needed?

Update for 0.6: yes, also coming very soon. #10

**Comment by rened** [comment]
Closing in favor of #9 and #10
